name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Rebuild frontend image
      run: npm run build:docker

    - name: Stop frontend
      run: npm run stop:docker

    - name: Start frontend
      run: npm run start:docker
